Fix paginate
just-work/bali pull request #1
Opened 2022-08-25 21:08 UTC by teg100

2022-08-26 05:12 UTC, tumb1er commented on requirements_dev.txt
> +https://github.com/just-work/pytest-grpc/archive/refs/tags/0.8.0+jw.1.zip
Это не дает нам возможности отправить PR в bali :(

Можешь альтернативы предложить? Как-нибудь захайдить фикстуру, которую мы ТАМ правили?

2022-08-26 05:13 UTC, tumb1er requested changes

2022-08-26 05:13 UTC, tumb1er commented on requirements_dev.txt
> +https://github.com/just-work/pytest-grpc/archive/refs/tags/0.8.0+jw.1.zip
Это не дает нам возможности отправить PR в bali :(

Можешь альтернативы предложить? Как-нибудь захайдить фикстуру, которую мы ТАМ правили?

2022-08-26 06:43 UTC, teg100 commented on requirements_dev.txt
> +https://github.com/just-work/pytest-grpc/archive/refs/tags/0.8.0+jw.1.zip
Тут получается какая-то безысходность. С одной стороны есть ошибка, которая появляется только в ассинхронном режиме и ее надо поправить, с другой зависимость которая реализует ассинхронный режим. Я не совсем понял твою мысль про фикстуру.

2022-08-26 08:02 UTC, tumb1er commented on requirements_dev.txt
> +https://github.com/just-work/pytest-grpc/archive/refs/tags/0.8.0+jw.1.zip
Мысль - завендорить зависимость в виде локального пакета-плагина. Только почистить неиспользуемые фикстуры, чтобы только минимально работоспособный тест поддержать.

2022-08-29 06:41 UTC, teg100 commented on requirements_dev.txt
> +https://github.com/just-work/pytest-grpc/archive/refs/tags/0.8.0+jw.1.zip
Исправил тест

2022-08-29 06:45 UTC, tumb1er requested changes

2022-08-29 06:45 UTC, tumb1er commented on tests/test_paginate.py
> +db.connect(DB_URI)
А это точно не отразится на тестах в других файлах?

2022-08-29 06:45 UTC, tumb1er commented on tests/test_paginate.py
> +        if str(e) == "Model instance can't parse to dict without schema":
А что в else?

2022-08-29 06:57 UTC, teg100 commented on tests/test_paginate.py
> +db.connect(DB_URI)
По другому не дает создать модель. Ошибка, что БД не инициализирована. Мы не создаем записи в БД сейчас, и этот коннект нужен просто для инициализации модели. Сейчас все тесты спокойно запускаются вместе и проходят.

2022-08-29 06:59 UTC, teg100 commented on tests/test_paginate.py
> +        if str(e) == "Model instance can't parse to dict without schema":
В этом моменте возникла сложность, не уверен, что решение оптимально. Таким образом хотел отдельно выделить, что именно проверяет этот тест. Если не эта ошибка, а что-то другое он также упадет.

2022-08-29 07:41 UTC, tumb1er commented on tests/test_paginate.py
> +        if str(e) == "Model instance can't parse to dict without schema":
А если другая ValueError?

2022-08-29 08:03 UTC, teg100 commented on tests/test_paginate.py
> +        if str(e) == "Model instance can't parse to dict without schema":
Тогда будет не обработано. Тут лучше сделать ветку else и просто в pytest.fail прокинуть текст ошибки? Так будет правильно?

2022-08-29 08:05 UTC, tumb1er commented on tests/test_paginate.py
> +        if str(e) == "Model instance can't parse to dict without schema":
Нас интересует, чтобы весь этот метод в пагинаторе отрабатывал успешно, а не возбуждал ошибки. Так что else - это тоже fail. И тогда вопрос, нужен ли вообще if? Или достаточно в комментарии указать, что тут было?

2022-08-29 08:20 UTC, teg100 commented on tests/test_paginate.py
> +        if str(e) == "Model instance can't parse to dict without schema":
Понял тебя. Поправил тест и докстринг к нему.

2022-08-29 08:25 UTC, tumb1er commented on tests/test_paginate.py
> +        if str(e) == "Model instance can't parse to dict without schema":
Я бы оставил try-except-fail, убрал только if. Даже с докстрингом кажется, что тест недописан (ассертов-то нет).

2022-08-29 08:29 UTC, teg100 commented on tests/test_paginate.py
> +        if str(e) == "Model instance can't parse to dict without schema":
Сделано :+1:

2022-08-29 08:29 UTC, tumb1er approved these changes

2022-08-29 08:29 UTC, merged